//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.05 at 10:33:19 AM GST 
//


package com.amt.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "body"
})
@XmlRootElement(name = "NIServices")
public class NIServicesRequest {

    @XmlElement(required = true)
    protected NIServicesRequest.Header header;
    @XmlElement(required = true)
    protected NIServicesRequest.Body body;

    public NIServicesRequest.Header getHeader() {
        return header;
    }

    public void setHeader(NIServicesRequest.Header value) {
        this.header = value;
    }

    public NIServicesRequest.Body getBody() {
        return body;
    }
   
    public void setBody(NIServicesRequest.Body value) {
        this.body = value;
    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "srvReq"
    })
    public static class Body {

        @XmlElement(name = "srv_req", required = true)
        protected NIServicesRequest.Body.SrvReq srvReq;

        
        public NIServicesRequest.Body.SrvReq getSrvReq() {
            return srvReq;
        }

        
        public void setSrvReq(NIServicesRequest.Body.SrvReq value) {
            this.srvReq = value;
        }


        
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "reqCreditCardBalanceEnquiry"
        })
        public static class SrvReq {

            @XmlElement(name = "req_credit_card_balance_enquiry", required = true)
            protected NIServicesRequest.Body.SrvReq.ReqCreditCardBalanceEnquiry reqCreditCardBalanceEnquiry;

            
            public NIServicesRequest.Body.SrvReq.ReqCreditCardBalanceEnquiry getReqCreditCardBalanceEnquiry() {
                return reqCreditCardBalanceEnquiry;
            }

            
            public void setReqCreditCardBalanceEnquiry(NIServicesRequest.Body.SrvReq.ReqCreditCardBalanceEnquiry value) {
                this.reqCreditCardBalanceEnquiry = value;
            }


            
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "cardNo"
            })
            public static class ReqCreditCardBalanceEnquiry {

                @XmlElement(name = "card_no", required = true)
                protected String cardNo;

               
                public String getCardNo() {
                    return cardNo;
                }

                
                public void setCardNo(String value) {
                    this.cardNo = value;
                }

            }

        }

    }


    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "version",
        "msgId",
        "msgType",
        "msgFunction",
        "srcApplication",
        "targetApplication",
        "timestamp",
        "trackingId",
        "bankId"
    })
    public static class Header {

        @XmlElement(required = true)
        protected String version;
        @XmlElement(name = "msg_id")
        protected long msgId;
        @XmlElement(name = "msg_type", required = true)
        protected String msgType;
        @XmlElement(name = "msg_function", required = true)
        protected String msgFunction;
        @XmlElement(name = "src_application", required = true)
        protected String srcApplication;
        @XmlElement(name = "target_application", required = true)
        protected String targetApplication;
        @XmlElement(required = true)
        protected String timestamp;
        @XmlElement(name = "tracking_id")
        protected long trackingId;
        @XmlElement(name = "bank_id", required = true)
        protected String bankId;

        
        public String getVersion() {
            return version;
        }

        
        public void setVersion(String value) {
            this.version = value;
        }

        
        public long getMsgId() {
            return msgId;
        }

        
        public void setMsgId(long value) {
            this.msgId = value;
        }

        
        public String getMsgType() {
            return msgType;
        }

        
        public void setMsgType(String value) {
            this.msgType = value;
        }

        
        public String getMsgFunction() {
            return msgFunction;
        }

        
        public void setMsgFunction(String value) {
            this.msgFunction = value;
        }

        
        public String getSrcApplication() {
            return srcApplication;
        }

        
        public void setSrcApplication(String value) {
            this.srcApplication = value;
        }

        
        public String getTargetApplication() {
            return targetApplication;
        }

        
        public void setTargetApplication(String value) {
            this.targetApplication = value;
        }

        
        public String getTimestamp() {
            return timestamp;
        }

        
        public void setTimestamp(String value) {
            this.timestamp = value;
        }

        
        public long getTrackingId() {
            return trackingId;
        }

        
        public void setTrackingId(long value) {
            this.trackingId = value;
        }

        
        public String getBankId() {
            return bankId;
        }

        
        public void setBankId(String value) {
            this.bankId = value;
        }

    }

}
