//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.05 at 10:33:19 AM GST 
//


package com.amt.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "body"
})
@XmlRootElement(name = "NIServices")
public class NIServicesResponse {

    @XmlElement(required = true)
    protected com.amt.testmodel.Header header;
    @XmlElement(required = true)
    protected com.amt.testmodel.Body body;

    


    public com.amt.testmodel.Header getHeader() {
		return header;
	}


	public void setHeader(com.amt.testmodel.Header header) {
		this.header = header;
	}


	public com.amt.testmodel.Body getBody() {
		return body;
	}


	public void setBody(com.amt.testmodel.Body body) {
		this.body = body;
	}


	@XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "srvRep"
    })
    public static class Body {

        @XmlElement(name = "srv_rep", required = true)
        protected NIServicesResponse.Body.SrvRep srvRep;

        
        public NIServicesResponse.Body.SrvRep getSrvRep() {
            return srvRep;
        }

        
        public void setSrvRep(NIServicesResponse.Body.SrvRep value) {
            this.srvRep = value;
        }


        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "exceptionDetails",
            "repCreditCardBalanceEnquiry"
        })
        public static class SrvRep {

            @XmlElement(name = "exception_details", required = true)
            protected NIServicesResponse.Body.SrvRep.ExceptionDetails exceptionDetails;
            @XmlElement(name = "rep_credit_card_balance_enquiry", required = true)
            protected NIServicesResponse.Body.SrvRep.RepCreditCardBalanceEnquiry repCreditCardBalanceEnquiry;

            
            public NIServicesResponse.Body.SrvRep.ExceptionDetails getExceptionDetails() {
                return exceptionDetails;
            }

            
            public void setExceptionDetails(NIServicesResponse.Body.SrvRep.ExceptionDetails value) {
                this.exceptionDetails = value;
            }

            
            public NIServicesResponse.Body.SrvRep.RepCreditCardBalanceEnquiry getRepCreditCardBalanceEnquiry() {
                return repCreditCardBalanceEnquiry;
            }

            
            public void setRepCreditCardBalanceEnquiry(NIServicesResponse.Body.SrvRep.RepCreditCardBalanceEnquiry value) {
                this.repCreditCardBalanceEnquiry = value;
            }


            
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "applicationName",
                "dateTime",
                "status",
                "errorCode",
                "errorDescription",
                "transactionRefId"
            })
            public static class ExceptionDetails {

                @XmlElement(name = "application_name", required = true)
                protected String applicationName;
                @XmlElement(name = "date_time", required = true)
                protected String dateTime;
                @XmlElement(required = true)
                protected String status;
                @XmlElement(name = "error_code")
                protected int errorCode;
                @XmlElement(name = "error_description", required = true)
                protected String errorDescription;
                @XmlElement(name = "transaction_ref_id")
                protected int transactionRefId;

                
                public String getApplicationName() {
                    return applicationName;
                }

               
                public void setApplicationName(String value) {
                    this.applicationName = value;
                }

               
                public String getDateTime() {
                    return dateTime;
                }

                
                public void setDateTime(String value) {
                    this.dateTime = value;
                }

                
                public String getStatus() {
                    return status;
                }

                
                public void setStatus(String value) {
                    this.status = value;
                }

                
                public int getErrorCode() {
                    return errorCode;
                }

                public void setErrorCode(int value) {
                    this.errorCode = value;
                }

                public String getErrorDescription() {
                    return errorDescription;
                }

                
                public void setErrorDescription(String value) {
                    this.errorDescription = value;
                }

                
                public int getTransactionRefId() {
                    return transactionRefId;
                }

               
                public void setTransactionRefId(int value) {
                    this.transactionRefId = value;
                }

            }


            
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "balanceEnquiry"
            })
            public static class RepCreditCardBalanceEnquiry {

                @XmlElement(name = "balance_enquiry", required = true)
                protected NIServicesResponse.Body.SrvRep.RepCreditCardBalanceEnquiry.BalanceEnquiry balanceEnquiry;

                
                public NIServicesResponse.Body.SrvRep.RepCreditCardBalanceEnquiry.BalanceEnquiry getBalanceEnquiry() {
                    return balanceEnquiry;
                }

                
                public void setBalanceEnquiry(NIServicesResponse.Body.SrvRep.RepCreditCardBalanceEnquiry.BalanceEnquiry value) {
                    this.balanceEnquiry = value;
                }


                
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "cardNo",
                    "cardBrand",
                    "cardCurrency",
                    "cardLimit",
                    "availableCredit",
                    "cashLimit",
                    "availableCash",
                    "outstandingBalance",
                    "expiryDate",
                    "overlimitFlag",
                    "overlimitAmount",
                    "minPayment",
                    "dueDate",
                    "unbilledAmount",
                    "pastDueFlag",
                    "pastDueAmount"
                })
                public static class BalanceEnquiry {

                    @XmlElement(name = "card_no", required = true)
                    protected String cardNo;
                    @XmlElement(name = "card_brand", required = true)
                    protected String cardBrand;
                    @XmlElement(name = "card_currency", required = true)
                    protected String cardCurrency;
                    @XmlElement(name = "card_limit")
                    protected int cardLimit;
                    @XmlElement(name = "available_credit")
                    protected int availableCredit;
                    @XmlElement(name = "cash_limit")
                    protected int cashLimit;
                    @XmlElement(name = "available_cash")
                    protected int availableCash;
                    @XmlElement(name = "outstanding_balance")
                    protected int outstandingBalance;
                    @XmlElement(name = "expiry_date", required = true)
                    protected String expiryDate;
                    @XmlElement(name = "overlimit_flag", required = true)
                    protected String overlimitFlag;
                    @XmlElement(name = "overlimit_amount")
                    protected int overlimitAmount;
                    @XmlElement(name = "min_payment")
                    protected int minPayment;
                    @XmlElement(name = "due_date", required = true)
                    protected String dueDate;
                    @XmlElement(name = "unbilled_amount")
                    protected int unbilledAmount;
                    @XmlElement(name = "past_due_flag", required = true)
                    protected String pastDueFlag;
                    @XmlElement(name = "past_due_amount")
                    protected int pastDueAmount;

                   
                    public String getCardNo() {
                        return cardNo;
                    }

                    
                    public void setCardNo(String value) {
                        this.cardNo = value;
                    }

                    
                    public String getCardBrand() {
                        return cardBrand;
                    }

                    
                    public void setCardBrand(String value) {
                        this.cardBrand = value;
                    }

                    
                    public String getCardCurrency() {
                        return cardCurrency;
                    }

                    
                    public void setCardCurrency(String value) {
                        this.cardCurrency = value;
                    }

                    
                    public int getCardLimit() {
                        return cardLimit;
                    }

                    
                    public void setCardLimit(int value) {
                        this.cardLimit = value;
                    }

                    
                    public int getAvailableCredit() {
                        return availableCredit;
                    }

                    
                    public void setAvailableCredit(int value) {
                        this.availableCredit = value;
                    }

                   
                    public int getCashLimit() {
                        return cashLimit;
                    }

                    
                    public void setCashLimit(int value) {
                        this.cashLimit = value;
                    }

                    
                    public int getAvailableCash() {
                        return availableCash;
                    }

                    
                    public void setAvailableCash(int value) {
                        this.availableCash = value;
                    }

                    
                    public int getOutstandingBalance() {
                        return outstandingBalance;
                    }

                    
                    public void setOutstandingBalance(int value) {
                        this.outstandingBalance = value;
                    }

                    
                    public String getExpiryDate() {
                        return expiryDate;
                    }

                    
                    public void setExpiryDate(String value) {
                        this.expiryDate = value;
                    }

                    
                    public String getOverlimitFlag() {
                        return overlimitFlag;
                    }

                    
                    public void setOverlimitFlag(String value) {
                        this.overlimitFlag = value;
                    }

                    
                    public int getOverlimitAmount() {
                        return overlimitAmount;
                    }

                    
                    public void setOverlimitAmount(int value) {
                        this.overlimitAmount = value;
                    }

                    
                    public int getMinPayment() {
                        return minPayment;
                    }

                    
                    public void setMinPayment(int value) {
                        this.minPayment = value;
                    }

                    
                    public String getDueDate() {
                        return dueDate;
                    }

                    
                    public void setDueDate(String value) {
                        this.dueDate = value;
                    }

                    
                    public int getUnbilledAmount() {
                        return unbilledAmount;
                    }

                    
                    public void setUnbilledAmount(int value) {
                        this.unbilledAmount = value;
                    }

                    
                    public String getPastDueFlag() {
                        return pastDueFlag;
                    }

                    
                    public void setPastDueFlag(String value) {
                        this.pastDueFlag = value;
                    }

                    
                    public int getPastDueAmount() {
                        return pastDueAmount;
                    }

                    
                    public void setPastDueAmount(int value) {
                        this.pastDueAmount = value;
                    }

                }

            }

        }

    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "version",
        "msgId",
        "msgType",
        "msgFunction",
        "srcApplication",
        "targetApplication",
        "timestamp",
        "trackingId",
        "bankId"
    })
    public static class Header {

        @XmlElement(required = true)
        protected String version;
        @XmlElement(name = "msg_id")
        protected long msgId;
        @XmlElement(name = "msg_type", required = true)
        protected String msgType;
        @XmlElement(name = "msg_function", required = true)
        protected String msgFunction;
        @XmlElement(name = "src_application", required = true)
        protected String srcApplication;
        @XmlElement(name = "target_application", required = true)
        protected String targetApplication;
        @XmlElement(required = true)
        protected String timestamp;
        @XmlElement(name = "tracking_id")
        protected long trackingId;
        @XmlElement(name = "bank_id", required = true)
        protected String bankId;

        
        public String getVersion() {
            return version;
        }

        
        public void setVersion(String value) {
            this.version = value;
        }

        
        public long getMsgId() {
            return msgId;
        }

        
        public void setMsgId(long value) {
            this.msgId = value;
        }

        
        public String getMsgType() {
            return msgType;
        }

        public void setMsgType(String value) {
            this.msgType = value;
        }

        
        public String getMsgFunction() {
            return msgFunction;
        }

        
        public void setMsgFunction(String value) {
            this.msgFunction = value;
        }

        
        public String getSrcApplication() {
            return srcApplication;
        }

        
        public void setSrcApplication(String value) {
            this.srcApplication = value;
        }

        
        public String getTargetApplication() {
            return targetApplication;
        }

        
        public void setTargetApplication(String value) {
            this.targetApplication = value;
        }

        
        public String getTimestamp() {
            return timestamp;
        }

        
        public void setTimestamp(String value) {
            this.timestamp = value;
        }

        
        public long getTrackingId() {
            return trackingId;
        }

        
        public void setTrackingId(long value) {
            this.trackingId = value;
        }

        
        public String getBankId() {
            return bankId;
        }

        
        public void setBankId(String value) {
            this.bankId = value;
        }

    }

}
