//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.05 at 10:33:19 AM GST 
//


package com.amt.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the amt package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: amt
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NIServicesResponse }
     * 
     */
    public NIServicesResponse createNIServicesResponse() {
        return new NIServicesResponse();
    }

    /**
     * Create an instance of {@link NIServicesRequest }
     * 
     */
    public NIServicesRequest createNIServicesRequest() {
        return new NIServicesRequest();
    }

    /**
     * Create an instance of {@link NIServicesRequest.Body }
     * 
     */
    public NIServicesRequest.Body createNIServicesRequestBody() {
        return new NIServicesRequest.Body();
    }

    /**
     * Create an instance of {@link NIServicesRequest.Body.SrvReq }
     * 
     */
    public NIServicesRequest.Body.SrvReq createNIServicesRequestBodySrvReq() {
        return new NIServicesRequest.Body.SrvReq();
    }

    /**
     * Create an instance of {@link NIServicesResponse.Body }
     * 
     */
    public NIServicesResponse.Body createNIServicesResponseBody() {
        return new NIServicesResponse.Body();
    }

    /**
     * Create an instance of {@link NIServicesResponse.Body.SrvRep }
     * 
     */
    public NIServicesResponse.Body.SrvRep createNIServicesResponseBodySrvRep() {
        return new NIServicesResponse.Body.SrvRep();
    }

    /**
     * Create an instance of {@link NIServicesResponse.Body.SrvRep.RepCreditCardBalanceEnquiry }
     * 
     */
    public NIServicesResponse.Body.SrvRep.RepCreditCardBalanceEnquiry createNIServicesResponseBodySrvRepRepCreditCardBalanceEnquiry() {
        return new NIServicesResponse.Body.SrvRep.RepCreditCardBalanceEnquiry();
    }

    /**
     * Create an instance of {@link NIServicesResponse.Header }
     * 
     */
    public NIServicesResponse.Header createNIServicesResponseHeader() {
        return new NIServicesResponse.Header();
    }

    /**
     * Create an instance of {@link NIServicesRequest.Header }
     * 
     */
    public NIServicesRequest.Header createNIServicesRequestHeader() {
        return new NIServicesRequest.Header();
    }

    /**
     * Create an instance of {@link NIServicesRequest.Body.SrvReq.ReqCreditCardBalanceEnquiry }
     * 
     */
    public NIServicesRequest.Body.SrvReq.ReqCreditCardBalanceEnquiry createNIServicesRequestBodySrvReqReqCreditCardBalanceEnquiry() {
        return new NIServicesRequest.Body.SrvReq.ReqCreditCardBalanceEnquiry();
    }

    /**
     * Create an instance of {@link NIServicesResponse.Body.SrvRep.ExceptionDetails }
     * 
     */
    public NIServicesResponse.Body.SrvRep.ExceptionDetails createNIServicesResponseBodySrvRepExceptionDetails() {
        return new NIServicesResponse.Body.SrvRep.ExceptionDetails();
    }

    /**
     * Create an instance of {@link NIServicesResponse.Body.SrvRep.RepCreditCardBalanceEnquiry.BalanceEnquiry }
     * 
     */
    public NIServicesResponse.Body.SrvRep.RepCreditCardBalanceEnquiry.BalanceEnquiry createNIServicesResponseBodySrvRepRepCreditCardBalanceEnquiryBalanceEnquiry() {
        return new NIServicesResponse.Body.SrvRep.RepCreditCardBalanceEnquiry.BalanceEnquiry();
    }

}
